cc_library(
    name = "ast",
    srcs = ["ExprAST.cpp"],
    hdrs = ["BinaryExprAST.h", "CallExprAST.h", "ExprAST.h", "FunctionAST.h", "NumberExprAST.h", "PrototypeAST.h", "VariableExprAST.h"],
    visibility = ["//visibility:public"]
)
